# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raoa.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'raoa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraoa.proto\"\x1f\n\nAgeRequest\x12\x11\n\tbirthYear\x18\x01 \x01(\x05\"\x1b\n\x08\x41geReply\x12\x0f\n\x07message\x18\x01 \x01(\t24\n\rAgeCalculator\x12#\n\x07TellAge\x12\x0b.AgeRequest\x1a\t.AgeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raoa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGEREQUEST']._serialized_start=14
  _globals['_AGEREQUEST']._serialized_end=45
  _globals['_AGEREPLY']._serialized_start=47
  _globals['_AGEREPLY']._serialized_end=74
  _globals['_AGECALCULATOR']._serialized_start=76
  _globals['_AGECALCULATOR']._serialized_end=128
# @@protoc_insertion_point(module_scope)
